
//Crear un usuario
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "userprueba2",
    "email": "userprueba2@userprueba2.com",
    "password": "prueba.1234",
    "edad": 30,
    "ciudad": "Madrid",
    "intereses": ["futbol"],
    "ofertas": true
}


###
//Iniciar cuenta de ususario
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "user25@test.com",
    "password": "testeos1234"
}

###
//Editar un usuario
PUT http://localhost:3000/api/users/user25@test.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJhOTE1YTIyY2Y0ZWEzNGM3NWIzZmEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidXNlcjI1QHRlc3QuY29tIiwiaWF0IjoxNzE0MDY1ODMwfQ.CaZ_Z0PJG-zN8OJGPbFpm4avgcD1498xKLUkWosEkmw

{
    "ciudad": "barcelona",
    "intereses": ["futbol", "tenis"],
    "ofertas": false
}

###
//Usuario puntuando una pagina web (registrado)
PUT http://localhost:3000/api/users/resena/B12345678
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJhODcyOTdiZjdjYzg2YWE0Zjg4YmUiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidXNlcnBydWViYTJAdXNlcnBydWViYTIuY29tIiwiaWF0IjoxNzE0MDYzMzQ0fQ.zV3N4ViK8U85f33wXOd4cjaAoVBKhp1_pUsrYtYSIm4
    
    {
        "scoring": "4",
        "resenas": "muy mala"
    }
###

//Borrar un usuario
DELETE http://localhost:3000/api/users/userprueba@userprueba.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIxNDc5YTI3MTMwYTUxYzM1MGRjOGYiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidXNlcnBydWViYUB1c2VycHJ1ZWJhLmNvbSIsImlhdCI6MTcxMzQ1NzA1M30.PHgcfhBPhY5TLYhA_rDiOfJlubesUUpHNADvFaBrAis

###
//Crear un comercio
POST http://localhost:3000/api/merchant HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWYyMzI2ZDVjNTBhODczZjk1ZGQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTMzODY5MTJ9.H16rF07akhaaI6FLd1rVb2X0MkxUKnQafa-kFhqvVuA

{
    "name": "comercio2",
    "CIF": "C12345678",
    "direccion": "CalleFalsa123",
    "email": "ccc@ccc.com",
    "phone": "123456789",
    "webpage": null
}


###

//Crar una pagina web para un comercio
PUT http://localhost:3000/api/merchant/C12345678 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJiNzJlZTY0YjQ1M2I3NGFhZGQ2MzciLCJyb2xlIjoibWVyY2hhbnQiLCJDSUYiOiJDMTIzNDU2NzgiLCJpYXQiOjE3MTQxMjM1MDJ9.60UV4OCGQfUgPpQk426Xlwz-PnIwWjNKt2zdCEpETAo

{
    "CIF": "C12345678",
    "webpage":{
        "ciudad": "Madrid",
        "actividad": "comercio",
        "titulo": "titulo2",
        "resumen": "resumen1",
        "textos": ["texto1"],
        "filename": "",
        "scoring":  null,
        "numeropuntuaciones": null,
        "resenas": null
    }
}

###
//meterImagen
PUT http://localhost:3000/api/merchant/upload/B12345678 HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjI0ZTcxODI4MjY0NjhlY2JlYjQwY2QiLCJyb2xlIjoibWVyY2hhbnQiLCJDSUYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MTM2OTQ0ODh9.MLbCAmYsXho7uqj0Qp6yhbK3JIc3QAqaa5FFQvC5WsE

--Boundry
Content-Disposition: form-data; name="file"; filename="img.png"
Content-Type: image/png

< ./img.png
--Boundry--


###
//ver imagen
GET http://localhost:3000/file-1713804105494.png HTTP/1.1
###
//Borrar un webPage
DELETE http://localhost:3000/api/merchant/B12345678?delete=webpage HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwZjc5YjU3NzQwYjkzOWJiNjE1MjIiLCJyb2xlIjoibWVyY2hhbnQiLCJDSUYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MTM0MzY1NzJ9.ef7RYNg_sTL7dUepWQ8yro9DyPNCaLh8E0qFECeE078

###
//Borrar un usuario merchant
DELETE http://localhost:3000/api/merchant/B12345678?delete=merchant HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIwZjc5YjU3NzQwYjkzOWJiNjE1MjIiLCJyb2xlIjoibWVyY2hhbnQiLCJDSUYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MTM0MzY1NzJ9.ef7RYNg_sTL7dUepWQ8yro9DyPNCaLh8E0qFECeE078

###
//Ver un comercio(solo puede el admin)
GET http://localhost:3000/api/merchant/B12345678 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWYyMzI2ZDVjNTBhODczZjk1ZGQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTMzODY5MTJ9.H16rF07akhaaI6FLd1rVb2X0MkxUKnQafa-kFhqvVuA

###
//Ver todos los comercios por filtro de ciudad y actividad
GET http://localhost:3000/api/merchant/?actividad=comercio&ciudad=Madrid&order=asc HTTP/1.1
Content-Type: application/json

###
//Ver los usuarios interesados
GET http://localhost:3000/api/users/?direccion=barcelona&intereses=futbol HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjI0ZTcxODI4MjY0NjhlY2JlYjQwY2QiLCJyb2xlIjoibWVyY2hhbnQiLCJDSUYiOiJCMTIzNDU2NzgiLCJpYXQiOjE3MTM2OTQ0ODh9.MLbCAmYsXho7uqj0Qp6yhbK3JIc3QAqaa5FFQvC5WsE

###
//Ver todos los comercios (solo puede el admin)
GET http://localhost:3000/api/merchant/todosLosComercios/prueba HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFlYWYyMzI2ZDVjNTBhODczZjk1ZGQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTMzODY5MTJ9.H16rF07akhaaI6FLd1rVb2X0MkxUKnQafa-kFhqvVuA

